# Generated by Django 5.0.6 on 2024-05-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_tag2_project2_delete_project_delete_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project2',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Tag2',
            new_name='Tag',
        ),
    ]
