# Generated by Django 5.0.6 on 2024-05-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_project2_project_rename_tag2_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
