# Generated by Django 5.0.6 on 2024-05-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='long_description',
        ),
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
