# Generated by Django 5.0.6 on 2024-06-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='default.png', upload_to='projects'),
        ),
    ]
