# Generated by Django 5.0.6 on 2024-06-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
